Overview:

1. We need Data to be in Computer Readable Format
2. When we have two or more sources of data, we need to perform data integration
3. Data inaccuracies need to be corrected - this process is called Data Cleansing
4. Some application might need data to be in a particular range. So, Normalization and or transformation of features is needed


What is the need to perform above steps?

Data obtained from Real world is completely raw. It may contains errors due to wrong data entry procedures or missing data or inconsistencies due to ill-handled data merged processes.

We are need the following three qualities in Data:
1. Accuracy
2. Completeness
3. Consistency

1. Data Integration

1.1 Finding Redundant Attributes

* Use Ï‡2 Correlation Test when data is nominal (What is nominal data? : In statistics, nominal data (also known as nominal scale) is a type of data that is used to label variables without providing any quantitative value. https://tinyurl.com/y7a2ndkl). The video helps in understanding this test: https://www.khanacademy.org/math/ap-statistics/chi-square-tests/chi-square-goodness-fit/v/chi-square-statistic

* Using Correlation coefficient and Covariance for numeric data

### Chi2 Statistic

In [34]:
# https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.chi2.html#sklearn.feature_selection.chi2

from sklearn.feature_selection import chi2
import pandas as pd # For reading data
import warnings
warnings.filterwarnings(action="ignore")

# Read data
heart_data = pd.read_csv("https://raw.githubusercontent.com/scherala/LearningML/master/Data/heart.csv")

# Separate features
nominal_features = ['anaemia', 'diabetes', 'high_blood_pressure', 'sex', 'smoking']
target_column = ['DEATH_EVENT']
numeric_features = set(heart_data.columns) - set(nominal_features) - set(target_column)

# Get Chi2 statistic
chi2_statistic, pvalues = chi2(heart_data[nominal_features], heart_data[target_column])

print("Chi2 Statistic: " )
print(chi2_statistic)

print("P Values:")
print(pvalues)

Chi2 Statistic:
[7.46593411e-01 6.56814450e-04 1.22153853e+00 1.95626598e-03
 3.23468288e-02]
P Values:
[0.38755692 0.97955374 0.26905893 0.96472131 0.85726857]

### Covariance and Correlation Coefficient:

In [46]:
heart_data_numeric = heart_data[numeric_features].join(heart_data[target_column])
heart_data_numeric.cov()

,creatinine_phosphokinase,age,ejection_fraction,time,platelets,serum_sodium,serum_creatinine,DEATH_EVENT
creatinine_phosphokinase,9.414586e+05,-941.591531,-506.174452,-703.803618,2.321533e+06,254.956443,-16.470382,28.464468
age,-9.415915e+02,141.486483,8.460237,-206.861351,-6.090712e+04,-2.412544,1.958845,1.411454
ejection_fraction,-5.061745e+02,8.460237,140.063455,38.330464,8.354524e+04,9.185787,-0.138379,-1.486667
time,-7.038036e+02,-206.861351,38.330464,6023.965276,7.981107e+04,30.014152,-11.988935,-19.127663
platelets,2.321533e+06,-60907.118586,83545.241001,79811.066099,9.565669e+09,26810.436905,-4168.399498,-2247.619159
serum_sodium,2.549564e+02,-2.412544,9.185787,30.014152,2.681044e+04,19.469956,-0.863173,-0.402819
serum_creatinine,-1.647038e+01,1.958845,-0.138379,-11.988935,-4.168399e+03,-0.863173,1.070211,0.142374
DEATH_EVENT,2.846447e+01,1.411454,-1.486667,-19.127663,-2.247619e+03,-0.402819,0.142374,0.218716

In [47]:
heart_data_numeric.corr()

,creatinine_phosphokinase,age,ejection_fraction,time,platelets,serum_sodium,serum_creatinine,DEATH_EVENT
creatinine_phosphokinase,1.000000,-0.081584,-0.044080,-0.009346,0.024463,0.059550,-0.016408,0.062728
age,-0.081584,1.000000,0.060098,-0.224068,-0.052354,-0.045966,0.159187,0.253729
ejection_fraction,-0.044080,0.060098,1.000000,0.041729,0.072177,0.175902,-0.011302,-0.268603
time,-0.009346,-0.224068,0.041729,1.000000,0.010514,0.087640,-0.149315,-0.526964
platelets,0.024463,-0.052354,0.072177,0.010514,1.000000,0.062125,-0.041198,-0.049139
serum_sodium,0.059550,-0.045966,0.175902,0.087640,0.062125,1.000000,-0.189095,-0.195204
serum_creatinine,-0.016408,0.159187,-0.011302,-0.149315,-0.041198,-0.189095,1.000000,0.294278
DEATH_EVENT,0.062728,0.253729,-0.268603,-0.526964,-0.049139,-0.195204,0.294278,1.000000